ProjetoEscola/Controllers/Entities/Aluno_DisciplinaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetoEscola.Models.CRUD;
using ProjetoEscola.Repositories.Consultas;
using ProjetoEscola.Repositories.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetoEscola.Controllers.Entities
{
    public class Aluno_DisciplinaController : Controller
    {
        private readonly IAluno_DisciplinaRepository _aluno_DisciplinaRepository;
        private Consultas consultas = new Consultas();

        public Aluno_DisciplinaController(IAluno_DisciplinaRepository aluno_DisciplinaRepository)
        {
            _aluno_DisciplinaRepository = aluno_DisciplinaRepository;
        }


        // GET: Aluno_DisciplinaController
        public async Task<IActionResult> Index()
        {
            return View(await _aluno_DisciplinaRepository.GetAluno_DisciplinaAsync());
        }

        // GET: Aluno_DisciplinaController/Details/5
        public async Task<IActionResult> Details(int? matricula_id,int? aluno_id,int? curso_id, int? disciplina_id)
        {
            if (matricula_id == null && aluno_id == null && curso_id == null && disciplina_id == null)
            {
                return NotFound();
            }

            var d = await _aluno_DisciplinaRepository
                .GetAluno_DisciplinaByIdAsync(matricula_id,aluno_id,curso_id,disciplina_id);
            if (d == null)
            {
                return NotFound();
            }

            return View(d);
        }

        // GET: Aluno_DisciplinaController/Create
        public ActionResult Create()
        {
            //valor temporario para preencher os valores do dropdown
            ViewBag.listamatriculas = consultas.RetornaListaMatriculas();
            ViewBag.listaAlunos = consultas.RetornaListaAlunos();
            ViewBag.listaCursos = consultas.RetornaListaCursos();
            ViewBag.listaDisciplinas = consultas.RetornaListaDisciplinas();

            return View();
        }

        // POST: Aluno_DisciplinaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,matricula_id,aluno_id,curso_id,disciplina_id,nota,status")] Aluno_Disciplina a)
        {
            if (ModelState.IsValid)
            {
                await _aluno_DisciplinaRepository.SaveAsync(a);

                return RedirectToAction(nameof(Index));
            }
            return View(a);
        }

        // GET: Aluno_DisciplinaController/Edit/5
        public async Task<IActionResult> Edit(int? matricula_id, int? aluno_id, int? curso_id, int? disciplina_id)
        {
           Aluno_Disciplina a = await _aluno_DisciplinaRepository.GetAluno_DisciplinaByIdAsync(matricula_id, aluno_id, curso_id, disciplina_id);

            if (a == null)
            {
                return NotFound();
            }

            ViewBag.listamatriculas = consultas.RetornaListaMatriculas();
            ViewBag.listaAlunos = consultas.RetornaListaAlunos();
            ViewBag.listaCursos = consultas.RetornaListaCursos();
            ViewBag.listaDisciplinas = consultas.RetornaListaDisciplinas();

            return View(a);
        }

        // POST: Aluno_DisciplinaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditConfirmed(int matricula_id, int aluno_id, int curso_id, int disciplina_id, [Bind("id,matricula_id,aluno_id,curso_id,disciplina_id,nota,status")] Aluno_Disciplina a)
        {
            if ( matricula_id != a.matricula_id && aluno_id != a.aluno_id && curso_id != a.curso_id && disciplina_id != a.disciplina_id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _aluno_DisciplinaRepository.UpdateAluno_DisciplinaAsync(a);

                }
                catch (DbUpdateConcurrencyException)
                {

                    throw;

                }
                return RedirectToAction(nameof(Index));
            }
            return View(a);
        }

        // GET: Aluno_DisciplinaController/Delete/5
        public async Task<IActionResult> Delete(int? matricula_id, int? aluno_id, int? curso_id, int? disciplina_id)
        {
            if ( matricula_id == null && aluno_id == null && curso_id == null && disciplina_id == null)
            {
                return NotFound();
            }

            var c = await _aluno_DisciplinaRepository.GetAluno_DisciplinaByIdAsync(matricula_id,aluno_id,curso_id,disciplina_id);
                

            if (c == null)
            {
                return NotFound();
            }

            return View(c);
        }

        // POST: Aluno_DisciplinaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? matricula_id, int? aluno_id, int? curso_id, int? disciplina_id)
        {
            await _aluno_DisciplinaRepository.DeleteAsync(matricula_id, aluno_id, curso_id, disciplina_id);
                
            return RedirectToAction(nameof(Index));
        }
    }
}

ProjetoEscola/Controllers/View/AlunoNotasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjetoEscola.Models.View;
using ProjetoEscola.Repositories.Consultas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetoEscola.Controllers.View
{
    public class AlunoNotasController : Controller
    {
        private Consultas consultas = new Consultas();

        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.listaDisciplinas = consultas.RetornaListaDisciplinas();
            return View();
        }

        [HttpPost]
        public IActionResult Buscar([Bind("aluno_id", "nome", "nomeDisciplina", "disciplina_id", "ano", "semestre", "nota")] AlunoNotasView a)
        {
            var displina_id = a.disciplina_id;
            var ano = a.ano;
            var semestre = a.semestre;

            ViewBag.listaDisciplinas = consultas.RetornaListaDisciplinas();
            ViewBag.lista = consultas.RetornaAlunoNotas(displina_id, ano, semestre);
            return View("~/Views/AlunoNotas/Listagem.cshtml");
        }
    }
}

ProjetoEscola/Controllers/View/AlunoPorCursoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjetoEscola.Models.View;
using ProjetoEscola.Repositories.Consultas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetoEscola.Controllers.View
{
    public class AlunoPorCursoController : Controller
    {
        private Consultas consultas = new Consultas();
        
        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.listaCursos = consultas.RetornaListaCursos();
            return View();
        }
      
        [HttpPost]
        public IActionResult Buscar([Bind("id","nome","curso_id","ano","semestre")] AlunoPorCursoView a)
        {
            var curso_id = a.curso_id;
            var ano = a.ano;
            var semestre = a.semestre;

            ViewBag.listaCursos = consultas.RetornaListaCursos();
            ViewBag.lista = consultas.RetornaAlunoPorCurso(curso_id, ano, semestre);
            return View("~/Views/AlunoPorCurso/Listagem.cshtml");
        }
    }
}

ProjetoEscola/Controllers/View/DisciplinasPorAlunoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjetoEscola.Models.View;
using ProjetoEscola.Repositories.Consultas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetoEscola.Controllers.View
{
    public class DisciplinasPorAlunoController : Controller
    {
        private Consultas consultas = new Consultas();

        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.listaAlunos = consultas.RetornaListaAlunos();
            return View();
        }

        [HttpPost]
        public IActionResult Buscar([Bind("aluno_id","nome", "nomeDisciplina","disciplina_id", "ano", "semestre","nota")] DisciplinasPorAlunoView d)
        {
            var aluno_id = d.aluno_id;
            var ano = d.ano;
            var semestre = d.semestre;

            ViewBag.listaAlunos = consultas.RetornaListaAlunos();
            ViewBag.lista = consultas.RetornaDisciplinasPorAluno(aluno_id, ano, semestre);
            return View("~/Views/DisciplinasPorAluno/Listagem.cshtml");
        }
    }
}

ProjetoEscola/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoEscola</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">E.E.B.B</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li>
                            <div class="dropdown">
                                <a href="#" class="nav-link text-dark dropdown-toggle" data-toggle="dropdown">
                                    Cadastros
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <li class="dropdown-item text-center-dark">@Html.ActionLink("Aluno", "Index", "Aluno", null, new { target = "_self" })</li>
                                    <li class="dropdown-item text-center-dark">@Html.ActionLink("Curso", "Index", "Curso", null, new { target = "_self" })</li>
                                    <li class="dropdown-item text-center-dark">@Html.ActionLink("Disciplina", "Index", "Disciplina", null, new { target = "_self" })</li>
                                </ul>
                            </div>
                        </li>

                        <li>
                            <div class="dropdown">
                                <a href="#" class="nav-link text-dark dropdown-toggle" data-toggle="dropdown">
                                    Relações
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <li class="dropdown-item text-center-dark">@Html.ActionLink("AlunoDisciplina", "Index", "Aluno_Disciplina", null, new { target = "_self" })</li>
                                    <li class="dropdown-item text-center-dark">@Html.ActionLink("CursoDisciplina", "Index", "Curso_Disciplina", null, new { target = "_self" })</li>
                                    <li class="dropdown-item text-center-dark">@Html.ActionLink("Matricula", "Index", "Matricula", null, new { target = "_self" })</li>
                                </ul>
                            </div>
                        </li>

                        <li>
                            <div class="dropdown">
                                <a href="#" class="nav-link text-dark dropdown-toggle" data-toggle="dropdown">
                                    Relatórios
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <li class="dropdown-item text-center-dark">@Html.ActionLink("Relatório 1", "Index", "AlunoPorCurso", null, new { target = "_self" })</li>
                                    <li class="dropdown-item text-center-dark">@Html.ActionLink("Relatório 2", "Index", "DisciplinasPorAluno", null, new { target = "_self" })</li>
                                    <li class="dropdown-item text-center-dark">@Html.ActionLink("Relatório 3", "Index", "AlunoNotas", null, new { target = "_self" })</li>
                                </ul>
                            </div>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ProjetoEscola - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>